# Generated by Django 5.0.6 on 2024-06-16 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quoteapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Autor",
            new_name="Author",
        ),
    ]
